name: Executar script Python a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Mantém credenciais para push

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar script Python
      run: |
        python verify_log.py &
        sleep 10
        pkill -f "python verify_log.py" || true

    - name: Commit do log atualizado
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add saida.txt
        git commit -m "Atualização automática do log [skip ci]" || echo "Nada a commitar"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}