name: Executar script Python a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        cd log-verifier
        pip install -r requirements.txt

    - name: Executar script Python
      run: |
        cd log-verifier
        python verify_log.py      
    - name: Commit do log atualizado
      run: |
        git config --global Jeff-green3002 "github-actions"
        git config --global jeferson.santos@softgreen.com.br "github-actions@github.com"
        git add saida.txt
        git commit -m "Atualização automática do log [skip ci]" || echo "Nada a commitar"
        git push
